name: Generate and Deploy Glossary

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: List directory structure
        run: |
          ls -la
          pwd

      - name: Create required directories
        run: |
          mkdir -p glossary
          mkdir -p data
          mkdir -p scripts

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set GEMINI_API_KEY environment variable
        run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" >> $GITHUB_ENV

      - name: Run glossary generator
        run: python scripts/glossary_generator.py

      - name: Configure Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"

      - name: Commit and push changes
        run: |
          git add glossary/ data/
          git commit -m "Generated new glossary pages [skip ci]" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
